--- 
title: "The Identification of Dynamic Structural Shocks"
author: "Kenza Benhima and Jean-Paul Renne"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
fontsize: 12pt
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "This course XXX."
css: "my-style.css"
---


<!-- Declare new latex code: -->
\newcommand{\bv}[1]{\mathbf{#1}} 

# The Identification of Dynamic Structural Shocks {#intro .unlisted .unnumbered}


<!-- # Before starting {#intro .unlisted .unnumbered} -->

The identification and estimation of dynamic responses to structural shocks is one of the principal goals of macroeconometrics. These responses correspond to the effect, over time, of an exogenous intervention that propagates through the economy, as modeled by a system of simultaneous equations.

<!-- As illustrated by Figure \@ref(fig:NgramIRF), that makes use of Google Ngram data, there is a close link between the development of "macroeconomic analysis" and the concept ofimpulse response functions. -->

<!-- ```{r NgramIRF, echo=FALSE,fig.cap="Source: Google Ngram. Fraction of books containing the blue and red keywords."} -->
<!-- library(ngramr) -->
<!-- keyw <- c("impulse response function","macroeconomic analysis") -->
<!-- res1 <- ngram(keyw[1],year_start = 1900);res2 <- ngram(keyw[2],year_start = 1900) -->
<!-- plot(res1$Year,res1$Frequency,type="l",lwd=2,xlab="",ylab="",col="blue",las=1) -->
<!-- lines(res2$Year,res2$Frequency,type="l",lwd=2,col="red") -->
<!-- legend("topleft", -->
<!--        keyw,lty=c(1),lwd=c(2), -->
<!--        col=c("blue","red")) -->
<!-- ``` -->


Over the last decades, several methodologies have been proposed so as to estimate these responses. The objective of this course, developed by [Kenza Benhima](https://sites.google.com/site/benhimakenza/) and [Jean-Paul Renne](https://sites.google.com/site/jeanpaulrenne/home), is to provide an exhaustive view of these methodologies and to provide students with tools enabling them to implement them in various contexts.

Codes associated with this course are part of the `IdSS` package (**Id**entification of **S**tructural **S**hocks), which is available on GitHub. To load a  package from GitHub, you need to use function `install_github` from the `devtools` package:

```{r installAEC, eval=FALSE}
install.packages("devtools") # in case you do not have already loaded this package.
library(devtools)
install_github("jrenne/IdSS")
library(IdSS)
```

**Useful (R) links:**

* Download R:

    *	R software: https://cran.r-project.org (the basic R software)
    *	RStudio: https://www.rstudio.com (a convenient R editor)

* Tutorials:

    *	Rstudio: https://dss.princeton.edu/training/RStudio101.pdf (by Oscar Torres-Reyna)
    *	R: https://cran.r-project.org/doc/contrib/Paradis-rdebuts_en.pdf (by Emmanuel Paradis)
    * My own tutorial: https://jrenne.shinyapps.io/Rtuto_publiShiny/


<!-- <!-- To specify the corresponding covariance matrix vcov. to be used, there are three possibilities: 1. It is pre-computed and supplied in argument vcov.. 2. A function for extracting the covariance matrix from x is supplied, e.g., sandwich, vcovHC, vcovCL, or vcovHAC from package sandwich.  -->
<!-- ```{r shp2,warning=FALSE,message=FALSE} -->
<!-- library(AEC) -->
<!-- library(sandwich) -->
<!-- shp$income <- shp$i19ptotn/1000 -->
<!-- shp$female <- 1*(shp$sex19==2) -->
<!-- eq <- lm(income ~ edyear19 + age19 + I(age19^2) + female,data=shp) -->
<!-- #eq <- lm(income ~ edyear19 + age19 + I(age19^2) + female + I(female*ownkid19*(age19<40)),data=shp) -->
<!-- #lmtest::coeftest(eq,vcov. = sandwich) -->
<!-- #lmtest::coeftest(eq,vcov. = vcovHC) -->
<!-- #X <- cbind(1,shp$edyear19,shp$age19,shp$age19^2,shp$female) -->
<!-- #solve(t(X) %*% X) %*% t(X) %*% diag(eq$residuals^2) %*% X %*% solve(t(X) %*% X) -->
<!-- #vcovHC(eq,type="HC0") -->
<!-- #sandwich(eq) -->
<!-- #vcovHC(eq,type="HC1") -->
<!-- ``` -->
<!-- XXXX HC0, HC1... Davidson MacKinnon 2004 Section 5.5 XXXX -->

<!-- **p.d.f. version**: [here](https://www.dropbox.com/s/td4bqpbzfuvwsev/ApplEcts.pdf?dl=0). -->




